CREATE TABLE xxdt_tasks
(
    task_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    project_id      NUMBER NOT NULL,
    task_name       VARCHAR2(200) NOT NULL,
    description     VARCHAR2(1000),
    status          VARCHAR2(30) DEFAULT 'TODO' NOT NULL,
    priority        VARCHAR2(20) DEFAULT 'MEDIUM' NOT NULL,
    due_date        DATE,
    created_by      VARCHAR2(255),
    created_date    DATE DEFAULT SYSDATE NOT NULL,
    updated_by      VARCHAR2(255),
    updated_date    DATE,

    CONSTRAINT xxdt_tasks_pk
        PRIMARY KEY (task_id),

    CONSTRAINT xxdt_tasks_project_fk
        FOREIGN KEY (project_id) REFERENCES xxdt_projects (project_id),

    CONSTRAINT xxdt_tasks_status_ck
        CHECK (status IN ('TODO', 'IN PROGRESS', 'COMPLETED', 'CANCELLED')),

    CONSTRAINT xxdt_tasks_priority_ck
        CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);
