CREATE TABLE xxdt_projects
(
    project_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    project_name    VARCHAR2(200) NOT NULL,
    description     VARCHAR2(1000),
    status          VARCHAR2(30) DEFAULT 'ACTIVE' NOT NULL,
    start_date      DATE,
    end_date        DATE,
    created_by      VARCHAR2(255),
    created_date    DATE DEFAULT SYSDATE NOT NULL,
    updated_by      VARCHAR2(255),
    updated_date    DATE,

    CONSTRAINT xxdt_projects_pk
        PRIMARY KEY (project_id),

    CONSTRAINT xxdt_projects_status_ck
        CHECK (status IN ('ACTIVE', 'ON HOLD', 'COMPLETED', 'CANCELLED')),

    CONSTRAINT xxdt_projects_dates_ck
        CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);